size(500, 500);
background(255);
stroke(0);
strokeWeight(5);
PVector poczatek = new PVector(0, 250);
PVector koniec = new PVector(500, 250);
PVector bok = PVector.sub(koniec, poczatek);
bok.div(3.0);
PVector P1 = PVector.add(poczatek, bok);
float k = 89;
bok.rotate(radians(k));
PVector P2 = PVector.add(P1, bok);
bok.rotate(radians(-2*k));
PVector P3 = PVector.add(P2, bok);
beginShape();
vertex(poczatek.x, poczatek.y);
vertex(P1.x, P1.y);
vertex(P2.x, P2.y);
vertex(P3.x, P3.y);
vertex(koniec.x, koniec.y);
endShape();
