size(500, 500);
background(255);
stroke(0);
strokeWeight(5);
PVector poczatek = new PVector(130, 200);
PVector koniec = new PVector(333, 346);
PVector srodek = PVector.sub(koniec, poczatek);
srodek.div(3.0);
srodek.add(poczatek);
line(poczatek.x, poczatek.y, koniec.x, koniec.y);
strokeWeight(15);
point(srodek.x, srodek.y);
